// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RevolvingCredit.Entity;
using System;

namespace RevolvingCredit.Entity.Migration
{
    [DbContext(typeof(RevolvingCreditContext))]
    partial class RevolvingCreditContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RevolvingCredit.Entity.Model.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountAPR", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("TypeId");

                    b.Property<DateTime>("UpdateTimestamp");

                    b.HasKey("AccountId", "TypeId", "UpdateTimestamp");

                    b.ToTable("AccountAPR");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountIssuer", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("IssuerId");

                    b.Property<DateTime>("UpdateTimestamp");

                    b.HasKey("AccountId", "IssuerId", "UpdateTimestamp");

                    b.ToTable("AccountIssuer");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountLabel", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("LabelId");

                    b.Property<DateTime>("UpdateTimestamp");

                    b.HasKey("AccountId", "LabelId", "UpdateTimestamp");

                    b.ToTable("AccountLabel");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountLine", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("LineId");

                    b.Property<DateTime>("UpdateTimestamp");

                    b.HasKey("AccountId", "LineId", "UpdateTimestamp");

                    b.ToTable("AccountLine");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountNote", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<DateTime>("UpdateTimestamp");

                    b.HasKey("AccountId", "UpdateTimestamp");

                    b.ToTable("AccountNote");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountPayment", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<DateTime>("Due");

                    b.Property<int>("TypeId");

                    b.HasKey("AccountId", "Due");

                    b.ToTable("AccountPayment");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountPromotion", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("TypeId");

                    b.Property<DateTime>("Start");

                    b.Property<DateTime>("End");

                    b.HasKey("AccountId", "TypeId", "Start", "End");

                    b.ToTable("AccountPromotion");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.AccountStatement", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<DateTime>("End");

                    b.HasKey("AccountId", "End");

                    b.ToTable("AccountStatement");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.APR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("APR");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.Issuer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Issuer");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("RevolvingCredit.Entity.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
